-- ============================================================================
-- 1. Доменные типы (ENUM)
-- ============================================================================
CREATE TYPE equipment_status AS ENUM (
    'exp',        -- эксплуатруемый
    'exp_int',    -- эксплуатруемый(интернет)
    'exp_sp',     -- эксплуатруемый(категорированный)
    'broken',     -- неисправно
    'written_off' -- списано
);

CREATE TYPE assignment_target AS ENUM (
    'employee',   -- Закреплен за сотрудником
    'department', -- Закреплен за подразделением
    'warehouse'   -- На складе
);

CREATE TYPE waybill_status AS ENUM ('DRAFT', 'SIGNED', 'ARCHIVED');

-- ============================================================================
-- 2. Справочные таблицы (Reference Entities)
-- ============================================================================
CREATE TABLE nomenclatures (
    id         int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    code       VARCHAR(50) NOT NULL UNIQUE,   -- код номенклатуры 08.01.02.00.00/0041
    name       VARCHAR(255) NOT NULL,         -- наименование (Ноутбук Clevo 15")
    created_at DATE DEFAULT CURRENT_DATE
);

CREATE TABLE employees (
    card_number   INT PRIMARY KEY,                     -- номер карточки (из КУ Ф-111)
    full_name     VARCHAR(150) NOT NULL,               -- ФИО ответственного (без звания)
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    DATE DEFAULT CURRENT_DATE
);

CREATE TABLE departments (
    id         INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    code       VARCHAR(50) NOT NULL UNIQUE,  -- код подразделения
    name       VARCHAR(150) NOT NULL UNIQUE, -- Наименование (Гомель ОПК, СКЛАД)
    is_active  BOOLEAN DEFAULT TRUE,
    created_at DATE DEFAULT CURRENT_DATE 
);

CREATE TABLE waybills (
    id         INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    number     VARCHAR(50) NOT NULL,  -- номер документа
    issue_date DATE        NOT NULL,  -- Дата документа (для отчётности)
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), -- Техническая метка создания
    status     waybill_status NOT NULL DEFAULT 'DRAFT'
);

-- ============================================================================
-- 3. Основная сущность: Оборудование (Aggregate Root)
-- ============================================================================
CREATE TABLE equipments (
    id                    INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    
    -- 🔑 Идентификаторы
    inventory_number      VARCHAR(7) NOT NULL UNIQUE CHECK (inventory_number ~ '^ИТ\d{5}$'),
    serial_number         VARCHAR(100),
    mac_address           VARCHAR(17),
    
    -- 📦 Классификация и атрибуты
    nomenclature_id       INT REFERENCES nomenclatures(id) ON DELETE RESTRICT,
    model_name            VARCHAR(255) NOT NULL,-- Модель
    manufacture_year      SMALLINT CHECK (manufacture_year BETWEEN 1990 AND 2200),
    arrival_date          DATE,                 -- Парсинг MM.YYYY → 1-е число месяца
    
    -- 🔄 Состояние
    status                equipment_status NOT NULL DEFAULT 'exp',
    form_number           VARCHAR(10),          -- № формуляра
    
    -- 📍 Локация (поле напрямую в таблице)
    location              VARCHAR(255),         -- № кабинета / место установки
    
    -- 📝 Метаданные
    notes                 TEXT,
    
    -- 🕒 Системные поля
    created_at            TIMESTAMPTZ DEFAULT NOW(),
    updated_at            TIMESTAMPTZ DEFAULT NOW(),
    deleted_at            TIMESTAMPTZ           -- Soft Delete
);

-- ============================================================================
-- 4. Позиции накладной (связь Waybill ↔ Equipment)
-- ============================================================================
CREATE TABLE waybill_items (
    waybill_id   INT NOT NULL REFERENCES waybills(id) ON DELETE CASCADE,
    equipment_id INT NOT NULL REFERENCES equipments(id) ON DELETE RESTRICT,
    PRIMARY KEY (waybill_id, equipment_id)
);

-- ============================================================================
-- 5. История и текущее закрепление (Domain Events / State)
-- ============================================================================
CREATE TABLE equipments_assignments (
    id              INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    equipment_id    INT NOT NULL REFERENCES equipments(id) ON DELETE CASCADE,
    
    -- Тип субъекта где закреплено оборудование
    target_type     assignment_target NOT NULL,
    
    -- Целевые ссылки (заполняются в зависимости от target_type)
    employee_id     INT REFERENCES employees(card_number) ON DELETE RESTRICT,
    department_id   INT REFERENCES departments(id) ON DELETE RESTRICT,
    waybill_id      INT REFERENCES waybills(id) ON DELETE RESTRICT,
    
    -- Временные метки
    assigned_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    unassigned_at   TIMESTAMPTZ,

    is_active       BOOLEAN NOT NULL DEFAULT TRUE,

    operator_comment TEXT,

    -- 🔒 ДОМЕННЫЕ ОГРАНИЧЕНИЯ (CHECK Constraints)
    CONSTRAINT chk_target_person CHECK (
        target_type = 'employee' AND 
        employee_id IS NOT NULL AND 
        department_id IS NULL AND
        waybill_id IS NULL
    ),
    CONSTRAINT chk_target_department CHECK (
        target_type = 'department' AND 
        department_id IS NOT NULL AND
        waybill_id IS NOT NULL AND 
        employee_id IS NULL 
    ),
    CONSTRAINT chk_target_warehouse CHECK (
        target_type = 'warehouse' AND 
        employee_id IS NULL AND 
        department_id IS NULL AND
        waybill_id IS NULL 
    )
);

-- ============================================================================
-- 6. Индексы и триггеры
-- ============================================================================
-- Быстрый поиск текущего закрепления
CREATE UNIQUE INDEX uq_active_assignment ON equipments_assignments(equipment_id) WHERE is_active = TRUE;
CREATE INDEX idx_eq_assignments_active ON equipments_assignments(equipment_id) WHERE is_active = TRUE;
-- История перемещений
CREATE INDEX idx_eq_assignments_history ON equipments_assignments(equipment_id, assigned_at DESC);

-- Частичные индексы для рабочих запросов (исключают soft-deleted записи)
CREATE INDEX idx_eq_status       ON equipments(status) WHERE deleted_at IS NULL;
CREATE INDEX idx_eq_nomenclature ON equipments(nomenclature_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_eq_location     ON equipments(location) WHERE deleted_at IS NULL;

-- Полнотекстовый индекс для поиска по наименованию/модели/серийнику
CREATE INDEX idx_eq_search ON equipments USING gin(
    to_tsvector('russian', model_name || ' ' || COALESCE(serial_number, ''))
);

-- Автообновление updated_at
CREATE OR REPLACE FUNCTION update_updated_at() RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_eq_updated_at BEFORE UPDATE ON equipments 
FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- 💡 Примечание к архитектуре:
-- 1. Номер карточки/накладной хранится в equipments_assignments, т.к. он привязан к факту передачи, 
--    а не к самой единице техники навсегда. Это позволяет вести полный аудит перемещений.
-- 2. CHECK-констрейнты жёстко запрещают невалидные комбинации (напр. склад + карточка).
-- 3. Все исключённые поля (СВТ, даты ремонта и т.д.) отсутствуют в схеме.